package cz.muni.chat.server.rest;

import jakarta.ws.rs.core.Application;
import org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition;
import org.eclipse.microprofile.openapi.annotations.info.Contact;
import org.eclipse.microprofile.openapi.annotations.info.Info;
import org.eclipse.microprofile.openapi.annotations.info.License;
import org.eclipse.microprofile.openapi.annotations.servers.Server;
import org.eclipse.microprofile.openapi.annotations.servers.ServerVariable;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;

// This class is normally generated by Quarkus at build time. However, if we want to configure OpenAPI with annotations, we need to add it manually like this.
// However, all of this can also be added by configuration (e.g., in application.properties)

@OpenAPIDefinition( // metadata for inclusion into OpenAPI document
    // see javadoc at https://javadoc.io/doc/io.swagger.core.v3/swagger-annotations/latest/index.html
    // see docs at https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
    info = @Info(title = "Example Chat Service",
        version = "1.1",
        description = """
                        Simple service for chatting. The API has operations for:
                        * getting all messages
                        * creating a new message
                        * getting messages in pages, i.e. last 20 messages or previous 20 messages
                        * getting a specific message by its id
                        
                        The description of the API in OpenAPI format is generated by
                        the tool [SpringDoc v2](https://springdoc.org/) from annotated Java classes,
                        mainly the controller class
                        [ChatRestController](https://github.com/martin-kuba/muni-chat-service/blob/main/chat-server/src/main/java/cz/muni/chat/server/rest/ChatRestController.java)
                        and the DTO classes in
                        [cz.muni.chat.server.facade](https://github.com/martin-kuba/muni-chat-service/tree/main/chat-server/src/main/java/cz/muni/chat/server/facade)
                        package.
                        """,
        contact = @Contact(name = "John Doe", email = "jdoe@ics.muni.cz", url = "https://www.muni.cz/lide/666-joe-doe"),
        license = @License(name = "Apache 2.0", url = "https://www.apache.org/licenses/LICENSE-2.0.html")
    ),
    servers = @Server(description = "my server", url = "{scheme}://{server}:{port}", variables = {
        @ServerVariable(name = "scheme", enumeration = {"http", "https"}, defaultValue = "http"),
        @ServerVariable(name = "server", defaultValue = "localhost"),
        @ServerVariable(name = "port", defaultValue = "8080"),
    })
)
@Tag(name = "Chat", description = "microservice for chat") // metadata for inclusion into OpenAPI document
public class ChatApplication extends Application {
}
