# set the path to the OpenAPI specification and the base of the repository
quarkus.openapi.generator.spec=../../../../../openapi.yaml
quarkus.openapi.generator.base-package=cz.muni.pa165.generated.server
