# set the path to the OpenAPI specification and the base of the repository
quarkus.openapi-generator.codegen.input-base-dir=../
quarkus.openapi-generator.codegen.include=openapi.yaml
quarkus.openapi-generator.codegen.spec.openapi_yaml.base-package=cz.muni.pa165.generated.client
quarkus.http.port=8088